name: Simple Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker://pandoc/core:2.9
        with:
          args: "main.tex -o index.html" # gets appended to pandoc command