name: Simple Usage

on: push

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  convert_via_pandoc:  
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3 # this gives the workflow access to your repository files
      - name: Run Pandoc on main tex file
        uses: docker://pandoc/core:2.16
        with:
          args: "main.tex -o index.html --toc --mathjax --standalone --css=main.css" # gets appended to pandoc command
      - name: Try and make a pdf from tex file
        uses: docker://4teamwork/pdflatex:20220403
        with:
          args: "main.tex"
        continue-on-error: true
      - name: Print Out Files 
        run: "ls ./* > test.html"          
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:          
          path: '.' # Upload entire repository
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
